project:
  type: website
  output-dir: _site
  title: "Phenofish"

website:
  title: "PHENOFISH"
  site-url: https://phenofish.github.io/
  repo-url: https://github.com/phenofish/phenofish.github.io/
  favicon: img/favicon/favicon-32x32.png
  search: false
  
  # sidebar:
  #   logo: images/logo-cesab.png
  
  page-footer: 
    left: "&copy; CC-BY [PHENOFISH group](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/phenofish/)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/phenofish/phenofish.github.io/)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true 
 
  navbar:
    logo: img/navbar-logo.png
    href: https://frbcesab.github.io/
    right:
    - text: "{{< fa house >}} <span class='menu-item'>Home</span>"
      href: index.qmd
    - text: "{{< fa users >}} <span class='menu-item'>People</span>"
      href: content/people.qmd
    - text: "{{< fa database >}} <span class='menu-item'>Database</span>"
      href: content/database.qmd
    - text: "{{< fa upload >}} <span class='menu-item'>Contributing</span>"
      href: content/contributing.qmd

format:
  html:
    theme: sandstone
    css: css/styles.css
    toc: false
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
